version: '3'

services:
  dev:
    container_name: swapi
    image: swapi
    ports:
      - 54321:3000
    env_file:
      - ./.env
    environment:
      PORT: 3000
      DATABASE_URL_DEV: ${DOCKER_DB_URL}
    command: sh -c "npm run db:ready && npm run dev"
    depends_on:
      - db
      - cache

  db:
    image: postgres
    ports:
      - 35432:5432
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DOCKER_DB_USER}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASS}
      POSTGRES_DB: ${DOCKER_DB}

  cache:
    image: redis
    env_file:
      - ./.env
    environment:
      REDIS_URL: ${REDIS_URL}
