  
openapi: 3.0.0
info:
  title: SWAPI
  description: The Star Wars API

  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  version: 1.0.0

externalDocs:
  description: Checkout the GitHub repo
  url: https://github.com/allebd/swapi

servers:
- url: /api/v1
  description: Localhost

tags:
- name: Home
  description: To get home page

paths:
  /: 
    get:
      tags:
        - Home
      summary: Home page
      responses:
        200:
          description: request successful
        404:
          description: Not Found
      security:
      - token: []

components:
  schemas:
    token:
      type: string
    home:
      type: object
      properties:
        message:
          type: string
          example: "Welcome to the Star Wars API!"
  
  securitySchemes:
    token:
      type: apiKey
      in: header
      name: authorization
